server:
  port: 8080
  servlet:
    context-path: /flutter
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/flutter-app"
    password: manhden123
    username: root
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:

      hibernate:
        format_sql: true


logging:
  level:
    web: debug
    sql: debug
    logging:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE


jwt:
  signKey: "BMliagU0/75yZMGvaPlC60aCgfKPVAiKFAoNTy7Caky98EtZ5CuAhKgrv1WwNr7c"